POST http://localhost:3003/
Content-Type: application/json

{
  "username":"haraujo",
  "password": "123456",
  "firstname":"Hugo",
  "lastname":"Araujo",
  "email":"haraujo@netcom.com",
  "mobilephone":"0414-4729605",
  "attribute":"haraujo",
	"op":":=" ,
	"value":"araujo",
	"groupname":"grupo1",
  "priority":1,
	"Pepe":"Pepa"
}

###
GET  http://localhost:3003/page/0

###

PUT  http://localhost:3003/
Content-Type: application/json

{
  "id":"14",
  "email":"haraujo@netcom.com"
}